<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

  <!-- To publish views instead of views.dll-->
    <EnableDefaultRazorGenerateItems>false</EnableDefaultRazorGenerateItems>
	<EnableDefaultRazorComponentItems>false</EnableDefaultRazorComponentItems>
	<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>


  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenPlaDiC.BIZ\OpenPlaDiC.BIZ.csproj" />
    <ProjectReference Include="..\OpenPlaDiC.DAL\OpenPlaDiC.DAL.csproj" />
    <ProjectReference Include="..\OpenPlaDiC.SF\OpenPlaDiC.SF.csproj" />
  </ItemGroup>

  <ItemGroup>
	    <!-- Explicitly include each .cshtml files in the subfolders under Views  -->
	  <Content Update="Views\**\*.cshtml" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components/" />
    <Folder Include="Views/Dashboard/" />
    <Folder Include="Views/DynamicView/" />
    <Folder Include="Views/EmailSettings/" />
    <Folder Include="Views/EntityManager/" />
    <Folder Include="Views/Error/" />
    <Folder Include="Views/Search/" />
    <Folder Include="Views/Security/" />
    <Folder Include="Views/Shared/Components/Breadcrumb/" />
    <Folder Include="Views/Shared/Components/Sidebar/" />
    <Folder Include="Views/SystemParameter/" />
  </ItemGroup>	

</Project>
